version: '3.9'
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mariadb:
    driver: local
  redis:
    driver: local

services:
  php-fpm:
    env_file: ./.env
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_SWOOLE_VERSION=${PHP_SWOOLE_VERSION}
    volumes:
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ${WWW_ROOT_PATH}/:/var/www
    expose:
      - "9000"
    ports:
      - "22:22"
      - "8000:8000"
      - "9501:9501"
      - "9502:9502"
      - "9503:9503"
    extra_hosts:
      - "dockerhost:10.0.75.0"
    environment:
      - PHP_IDE_CONFIG=serverName=twitf
    networks:
      - backend
    container_name: php${PHP_VERSION}-fpm
  mariadb:
    env_file: ./.env
    build:
      context: ./mariadb
    volumes:
      - ${DATA_PATH}/mariadb:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - backend
    container_name: mariadb
  redis:
    env_file: ./.env
    build: ./redis
    volumes:
      - ${DATA_PATH}/redis:/data
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
    container_name: redis
  rabbitmq:
    env_file: ./.env
    build: ./rabbitmq
    volumes:
      - ${DATA_PATH}/rabbitmq:/var/lib/rabbitmq
    ports:
      - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - backend
    container_name: rabbitmq
