version: '3'
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mariadb:
    driver: local
  mongo:
    driver: local
  redis:
    driver: local
  phpmyadmin:
    driver: local
  elasticsearch:
    driver: local

services:

  ### PHP-FPM ##############################################
  php-fpm:
    env_file: ./.env
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ../:/var/www
    expose:
      - "9000"
    ports:
      - "22:22"
      - "9501:9501"
      - "9502:9502"
      - "9503:9503"
      - "8000:8000"
    extra_hosts:
      - "dockerhost:10.0.75.0"
    environment:
      - PHP_IDE_CONFIG=serverName=twitf
    networks:
      - backend
    container_name: php${PHP_VERSION}-fpm

  ### NGINX Server #########################################
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/var/www
      - ./logs/nginx:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/ssl/:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
    container_name: nginx

  ### MariaDB ################################################
  mariadb:
    build:
      context: ./mariadb
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=twitf
      - MYSQL_PASSWORD=twitf
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mariadb:/var/lib/mysql
      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - backend
    container_name: mariadb
  ### MongoDB ##############################################
  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - backend
    container_name: mongo
  ### Redis ################################################
  redis:
    build: ./redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - backend
    container_name: redis

  ### phpMyAdmin ###########################################
  phpmyadmin:
    build: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=default
      - MYSQL_PASSWORD=twitf
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - "mariadb"
    networks:
      - frontend
      - backend
    container_name: phpmyadmin

  ### ElasticSearch ########################################
  elasticsearch:
    build: ./elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - cluster.name=twitf-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
    container_name: elasticSearch

  ### RabbitMQ ########################################
  rabbitmq:
    build: ./rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15671:15671"
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    depends_on:
      - php-fpm
    networks:
      - backend
    container_name: rabbitmq
